AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvName:
    Type: String
  DbStorageGbs:
    Type: String
    Default: 20
  DbBackupDays:
    Type: String
    Default: 7
  DbInstanceClass:
    Type: String
    Default: db.t2.small
  DbMultiAz:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  DbAdminPassword:
    Type: String
    NoEcho: true
  WebInstanceType:
    Type: String
    Default: t2.micro
  OauthToken:
    Type: String

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${EnvName}-Db
      DBSubnetGroupDescription: DB Subnet Group
      SubnetIds:
        - subnet-19bfcb7f
        - subnet-f5c054bd
        - subnet-4097a11b

  ProdDbAccessSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvName}-ProdDbAccess
      GroupDescription: Prod DB Access Security Group
      VpcId: vpc-172f0c71

  ProdDbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvName}-ProdDb
      GroupDescription: Prod DB Security Group
      VpcId: vpc-172f0c71
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ProdDbAccessSg

  ProdDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DbStorageGbs
      BackupRetentionPeriod: !Ref DbBackupDays
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DbInstanceClass
      DBInstanceIdentifier: !Sub ${EnvName}-ProdDb
      DBName: ebdb
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine: mysql
      EngineVersion: 5.7.21
      MasterUsername: Admin
      MasterUserPassword: !Ref DbAdminPassword
      MultiAZ: true
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref ProdDbSg
        
  StageDbAccessSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvName}-StageDbAccess
      GroupDescription: Stage DB Access Security Group
      VpcId: vpc-172f0c71

  StageDbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvName}-StageDb
      GroupDescription: Stage DB Security Group
      VpcId: vpc-172f0c71
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref StageDbAccessSg
        
  StageDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DbStorageGbs
      BackupRetentionPeriod: !Ref DbBackupDays
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DbInstanceClass
      DBInstanceIdentifier: !Sub ${EnvName}-StageDb
      DBName: ebdb
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine: mysql
      EngineVersion: 5.7.21
      MasterUsername: Admin
      MasterUserPassword: !Ref DbAdminPassword
      MultiAZ: false
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref StageDbSg

  EbApp:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub ${EnvName}-app

  EbInstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier

  EbInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EbInstanceProfileRole

  ProdEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref EbApp
      EnvironmentName: Prod
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.7.0 running PHP 7.1
      Tier:
        Name: WebServer
        Type: Standard
      OptionSettings:
        - Namespace: "aws:ec2:vpc"
          OptionName: VPCId
          Value: vpc-172f0c71
        - Namespace: "aws:ec2:vpc"
          OptionName: Subnets
          Value: "subnet-19bfcb7f,subnet-f5c054bd"
        - Namespace: "aws:ec2:vpc"
          OptionName: ELBSubnets
          Value: "subnet-19bfcb7f,subnet-f5c054bd"
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: IamInstanceProfile
          Value: !Ref EbInstanceProfile
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: EC2KeyName
          Value: jjk3@nimbusscale.com
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: InstanceType
          Value: !Ref WebInstanceType
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: SecurityGroups
          Value: !Ref ProdDbAccessSg
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_HOSTNAME
          Value: !GetAtt ProdDb.Endpoint.Address
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_PORT
          Value: !GetAtt ProdDb.Endpoint.Port
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_DB_NAME
          Value: ebdb
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_USERNAME
          Value: Admin
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_PASSWORD
          Value: !Ref DbAdminPassword
          
  StageEnv:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref EbApp
      EnvironmentName: Stage
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.7.0 running PHP 7.1
      Tier:
        Name: WebServer
        Type: Standard
      OptionSettings:
        - Namespace: "aws:ec2:vpc"
          OptionName: VPCId
          Value: vpc-172f0c71
        - Namespace: "aws:ec2:vpc"
          OptionName: Subnets
          Value: "subnet-19bfcb7f,subnet-f5c054bd"
        - Namespace: "aws:ec2:vpc"
          OptionName: ELBSubnets
          Value: "subnet-19bfcb7f,subnet-f5c054bd"
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: IamInstanceProfile
          Value: !Ref EbInstanceProfile
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: EC2KeyName
          Value: jjk3@nimbusscale.com
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: InstanceType
          Value: !Ref WebInstanceType
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: SecurityGroups
          Value: !Ref StageDbAccessSg
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_HOSTNAME
          Value: !GetAtt StageDb.Endpoint.Address
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_PORT
          Value: !GetAtt StageDb.Endpoint.Port
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_DB_NAME
          Value: ebdb
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_USERNAME
          Value: Admin
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: RDS_PASSWORD
          Value: !Ref DbAdminPassword

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: PipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
              - rds:*
              - autoscaling:*
              - iam:PassRole
              - elasticfilesystem:*
              - s3:*
              - cloudformation:*
              - elasticloadbalancing:*
              - elasticbeanstalk:*
              - cloudwatch:*
              - ec2:*
              Resource: "*"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${EnvName}-pipeline
      ArtifactStore:
        Type: S3
        Location: codepipeline-us-west-2-971109881568
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                  Owner: nimbusscale
                  Repo: eb-code
                  Branch: master
                  PollForSourceChanges: true
                  OAuthToken: !Ref OauthToken
              Name: SourceFromGithub
              OutputArtifacts:
                - Name: wordpress
        - Name: Deploy
          Actions:
            - Name: DeployToEb
              InputArtifacts:
                - Name: wordpress
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ElasticBeanstalk
                Version: 1
              Configuration:
                ApplicationName: !Ref EbApp
                EnvironmentName: !Ref StageEnv





